title: Gengar
email: null
description: A blog for sharing my thoughts and, maybe, some technical stuff.
url: "https://gengar0xff.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gengar0xff
github_username:  gengar0xff
theme: null

